### ISSUE TITLE
very similar issue to #9

### ISSUE THREAD

**Issue by Therrk** [MartyMcKnife/BeatSaberSpotify#15]
None of the fixes mentioned there, or in any other issue seem to work.

The program behaves the same as it does in #9, once everything has been entered and I press start, nothing happens, as can be shown here

https://user-images.githubusercontent.com/43972622/104785303-2d14ab80-5758-11eb-88e2-626e9c99637a.mp4

Spotify URI: spotify:user:31o2reqae6kmogtegb2gimf65gpm:playlist:4dcNOTYGGftoEQJAkwHG0W
Probably noteworthy that the program is located on the same drive as the python install, which is a different drive than the beat saber install.

I also tried uninstalling python 3.9.1 and installing 3.9.0, same behavior

**Comment by MartyMcKnife** [comment]
I know it seems kinda silly, but have you tried just waiting? In the video, you seem to click start and then almost immediately hit stop. The program takes a couple of seconds to spool up, before actually showing anything in the output

Failing that, is there a log file? That'll make debugging a lot easier

**Comment by Therrk** [comment]
Sadly, I'm not even double clicking, the program just switches from start to stop instantly, I'm not double clicking.

and no sadly, the program doesn't make a log file

tell me if I can do anything else to help!

**Comment by MartyMcKnife** [comment]
Ah ok. That means the python side of the code isn't evening running. 

Where is the path to your python install? And did you add it to PATH? Might just be it can't find it

**Comment by MartyMcKnife** [comment]
Merging to #18
