### ISSUE TITLE
Having the same issue as #13, but no log comes out either.

### ISSUE THREAD

**Issue by matthiasdevreede** [MartyMcKnife/BeatSaberSpotify#18]
I've installed the newest release (V2.1.2), I've updated everything that was required. Provided my spotify playlist URL (spotify:playlist:6YjKA95eWhI7K4bJBIiEWc), my Username, Headset and a blank folder to see what it'd put in there, but 
1. Pressing the start button doesnt do anything.
2. No log comes out of the application.

**Comment by MartyMcKnife** [comment]
Well that's 4 people now that have had the same problem, so there's obviously something major going wrong

Can you try

1.  Pressing Win + R, and type `python.exe`. A console window should pop up
2. Open up cmd, and paste `python -c "import sys; print(sys.executable)"`. Give me the output of that

With any luck, we'll be able to isolate the situation

**Comment by matthiasdevreede** [comment]
Alright, I've come a bit further. typing python in win + R brought me to the Microsoft store to download Python (Even though I installed it through the site yesterday) After trying again to see if that did anything the start button actually did something, but comes out with an error, am yet to find a log file though. This is what comes out of the program itself

`Requirement already satisfied: requests in c:\users\matthias\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (2.25.1)
Requirement already satisfied: idna<3,>=2.5 in c:\users\matthias\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\matthias\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\matthias\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests) (1.26.3)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\matthias\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from requests) (4.0.0)
Requirement already satisfied: fuzzywuzzy in c:\users\matthias\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (0.18.0)
Collecting python-Levenshtein
  Using cached python-Levenshtein-0.12.2.tar.gz (50 kB)
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\site-packages (from python-Levenshtein) (49.2.1)
Using legacy 'setup.py install' for python-Levenshtein, since package 'wheel' is not installed.
Installing collected packages: python-Levenshtein
    Running setup.py install for python-Levenshtein: started
    Running setup.py install for python-Levenshtein: finished with status 'error'
`

Additionally here's the output to `python -c "import sys; print(sys.executable)"`
C:\Users\Matthias\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe

Thanks for the quick response.

**Comment by MartyMcKnife** [comment]
Ah ha! That'll be it. I thought I resolved this maaaaaaaaaaany issues ago, though I didn't think it would affect everyone. 
Basically, windows put Python on the Microsoft store, and any attempt to use python without installing it from there first would cause it to open the Microsoft store, for the user to install it. I'll make sure to write up a notice, so this hopefully doesn't happen again

As for that error, it should resolve itself by running the program again. If not, just run `pip install python-Levenshtein` and `pip install python-Levenshtein-wheels`

Thanks for helping me narrow down the issue!
