### ISSUE TITLE
Doesnt finish the playlist

### ISSUE THREAD

**Issue by Doredude12** [MartyMcKnife/BeatSaberSpotify#2]
I'm not 100% sure if it is done or not. but it doesn't complete the entire playlist.
[beatsaverspotify.log](https://github.com/MartyMcKnife/BeatSaberSpotify/files/4767798/beatsaverspotify.log)
I looked in the dir. and didn't see anything remotely related to what the file is saying.
I hope it can be worked out, this is such a great idea.

Edit: after reading this I seem to need to clarify a little, I know that not all songs are going to have a map for them, it gets to a select song and stops finding songs anymore. Sorry my wording is meh at best.

**Comment by MartyMcKnife** [comment]
Huh. That's a bit weird. The fact that it doesn't download most of your playlist is normal - at the moment it just queries beatsaver, and sees if the song exists. However, you seem to get a lot of error messages, some of which stopping the program to complete. I'll look at it in more depth tomorrow - hopefully I can push a fix soon

**Comment by MartyMcKnife** [comment]
Ok, it was a pretty critical bug, which meant that any song with a slash in it, the program would treat it as a path. It is now fixed with the latest update
