### ISSUE TITLE
Now the program runs, but errors out

### ISSUE THREAD

**Issue by Therrk** [MartyMcKnife/BeatSaberSpotify#21]
I'm one of the 4 people who had trouble with the program not doing anything once pressing start.
Now it runs, big thanks, but inputting the same things as last time, in #15.

Now, I've got another problem, it now starts, and outputs this to the dialog box:

Requirement already satisfied: requests in c:\users\elie\appdata\local\programs\python\python39\lib\site-packages (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\elie\appdata\local\programs\python\python39\lib\site-packages (from requests) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\elie\appdata\local\programs\python\python39\lib\site-packages (from requests) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\elie\appdata\local\programs\python\python39\lib\site-packages (from requests) (1.26.3)
Requirement already satisfied: idna<3,>=2.5 in c:\users\elie\appdata\local\programs\python\python39\lib\site-packages (from requests) (2.10)
Requirement already satisfied: fuzzywuzzy in c:\users\elie\appdata\local\programs\python\python39\lib\site-packages (0.18.0)
Collecting python-Levenshtein
  Using cached python-Levenshtein-0.12.2.tar.gz (50 kB)
Requirement already satisfied: setuptools in c:\users\elie\appdata\local\programs\python\python39\lib\site-packages (from python-Levenshtein) (49.2.1)
Using legacy 'setup.py install' for python-Levenshtein, since package 'wheel' is not installed.
Installing collected packages: python-Levenshtein
    Running setup.py install for python-Levenshtein: started
    Running setup.py install for python-Levenshtein: finished with status 'error'

There seems to be a problem with the installation of python-Levenshtein, caused by the missing 'wheel' package, but my very very basic understanding of python doesn't let me understand anything more

**Comment by MartyMcKnife** [comment]
Well at least it runs! :p 

I quite literally just had this error with another person. It can be solved by re-running, or running `pip install python-Levenshtein` and `pip install python-Levenshtein-wheels`

However, the fact that it's appeared twice might mean I need to change the package, to improve stability

Just as an aside, if you get an error that comes from the youtube-scrape module, that means you've been rate limited. Just wait a couple minutes, and run it again. I'm making it more clear in the next update

**Comment by Therrk** [comment]
hum so something maybe wrong with my install of python then, because entering pip install python-Levenshtein, and pip install python-Levenshtein-wheels return this:
'pip' is not recognized as an internal or external command,
operable program or batch file.

So it seems my computer can't even find pip so it makes sense it can't install py modules using it.
which is even weirder, because PyCharm works perfectly.

**Comment by MartyMcKnife** [comment]
Try running pip3 or reinstalling pip. If that doesn't work, I'm not sure I'm the best person to ask for help. Your best bet would be creating an issue over at [pip's github page.](https://github.com/pypa/pip/issues)

**Comment by Therrk** [comment]
So the problem was that pip wasn't in my PATH variable, and it's happened twice now on different computers, so I think I'm installing Python wrong

**Comment by MartyMcKnife** [comment]
Right I'm gonna reopen this issue, just as it because it isn't really resolved

I'm not sure exactly how you're installing pip, but the way that always works for me is running

`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`

then 

`python get-pip.py`

**Comment by Therrk** [comment]
it installed itself with python, and I distinctly remember not being very sure about some install options, especially those who mentioned the PATH variable, so I probably just chose the wrong option on an install file.

If anyone happens to fall here somewhere in the future with a similar problem, what fixed it for me is:
https://datatofish.com/add-python-to-windows-path/

**Comment by MartyMcKnife** [comment]
👍

**Comment by alzahhar3** [comment]
I am having the same error even after the latest update, well I think it is a similar one anyway. Btw I know my way around a computer but I have 0 programming experience.

Here is what I get 
"
Requirement already satisfied: requests in c:\users\my_user\appdata\local\programs\python\python39\lib\site-packages (2.25.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\my_user\appdata\local\programs\python\python39\lib\site-packages (from requests) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\my_user\appdata\local\programs\python\python39\lib\site-packages (from requests) (1.26.3)
Requirement already satisfied: idna<3,>=2.5 in c:\users\my_user\appdata\local\programs\python\python39\lib\site-packages (from requests) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\my_user\appdata\local\programs\python\python39\lib\site-packages (from requests) (4.0.0)
Requirement already satisfied: fuzzywuzzy in c:\users\my_user\appdata\local\programs\python\python39\lib\site-packages (0.18.0)
Collecting python-Levenshtein
  Using cached python-Levenshtein-0.12.2.tar.gz (50 kB)
Requirement already satisfied: setuptools in c:\users\my_user\appdata\local\programs\python\python39\lib\site-packages (from python-Levenshtein) (49.2.1)
Building wheels for collected packages: python-Levenshtein
  Building wheel for python-Levenshtein (setup.py): started
  Building wheel for python-Levenshtein (setup.py): finished with status 'error'
  Running setup.py clean for python-Levenshtein
Failed to build python-Levenshtein
Installing collected packages: python-Levenshtein
    Running setup.py install for python-Levenshtein: started
    Running setup.py install for python-Levenshtein: finished with status 'error'
"

When I run the cmd commands mentioned before (I assume that's what they are)


`pip install python-Levenshtein`

brings back a whole lot of red text and errors

`pip install python-Levenshtein-wheels`

brings back "Requirement already satisfied: python-Levenshtein-wheels"

`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
`
then
`python get-pip.py
`
works fine

I followed this as well as it was suggested here 
https://datatofish.com/add-python-to-windows-path/
and it did not solve the issue

**Comment by MartyMcKnife** [comment]
Basically, python-Levenshtein doesn't like installing on Windows. It should just skip over the error and install python-Levenshtein-wheels instead.

All I can say is try running it again. If not, I might try removing the python-Levenshtein package altogether

**Comment by alzahhar3** [comment]
I've tried running it many times and I get the same error every time unfortunately, and I am sorry to bother you but this is a great program that I'd love to use!

**Comment by MartyMcKnife** [comment]
Alright, we'll try removing the problem, and see if that fixes things

Can you open the `python` folder, and then open `beatsaver.py`.

Delete the line that says `install("python-Levenshtein")` , and then try running it again

**Comment by alzahhar3** [comment]
> Alright, we'll try removing the problem, and see if that fixes things
> 
> Can you open the `python` folder, and then open `beatsaver.py`.
> 
> Delete the line that says `install("python-Levenshtein")` , and then try running it again

aaand that fixed it! It donwloaded almost all my songs. Thanks for the help.

**Comment by MartyMcKnife** [comment]
Woohoo!

I'll make sure to fix that right away :)
