### ISSUE TITLE
Missing components? Not sure how to install in this case

### ISSUE THREAD

**Issue by rustjakey** [MartyMcKnife/BeatSaberSpotify#24]
```Requirement already satisfied: requests in c:\users\jakey\appdata\local\programs\python\python39\lib\site-packages (2.25.1)
Requirement already satisfied: idna<3,>=2.5 in c:\users\jakey\appdata\local\programs\python\python39\lib\site-packages (from requests) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\jakey\appdata\local\programs\python\python39\lib\site-packages (from requests) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jakey\appdata\local\programs\python\python39\lib\site-packages (from requests) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\jakey\appdata\local\programs\python\python39\lib\site-packages (from requests) (1.26.4)
Requirement already satisfied: fuzzywuzzy in c:\users\jakey\appdata\local\programs\python\python39\lib\site-packages (0.18.0)
Collecting python-Levenshtein
  Using cached python-Levenshtein-0.12.2.tar.gz (50 kB)
Requirement already satisfied: setuptools in c:\users\jakey\appdata\local\programs\python\python39\lib\site-packages (from python-Levenshtein) (49.2.1)
Using legacy 'setup.py install' for python-Levenshtein, since package 'wheel' is not installed.
Installing collected packages: python-Levenshtein
    Running setup.py install for python-Levenshtein: started
    Running setup.py install for python-Levenshtein: finished with status 'error'
```

**Comment by rustjakey** [comment]
![image](https://user-images.githubusercontent.com/79246335/115415317-da8bd500-a207-11eb-85f9-d8f5aed7cca3.png)
Still occurs after installing laters VC redist and above

**Comment by MartyMcKnife** [comment]
I think you might have installed the wrong version. `python-Levenshtein` should not be in the latest version

In any case, just open up the file in /python called beatsaver.py, and remove the line that says `    install("python-Levenshtein")`

**Comment by rustjakey** [comment]
[beatsaberspotify.log](https://github.com/MartyMcKnife/BeatSaberSpotify/files/6351087/beatsaberspotify.log)

**Comment by rustjakey** [comment]
Unsure why this is, ive tried to get the URL from the website as well, as the button the wiki shows to get the playlist link has disappeared. 

Even with the url like this ```https://open.spotify.com/playlist/4sQ7MiKKKW64vKLuDGdRsR``` it doesnt work, I also tried the right click copy share link to playlist

**Comment by MartyMcKnife** [comment]
Merging with #25, as its the same issue


Can you try the command I posted there?

**Comment by rustjakey** [comment]
I have, the new error is regarding spotify API access, I posted the error
log.

The initial issue of the levenshtein install was fixed by your suggestion.

**Comment by MartyMcKnife** [comment]
Yes, I understand that.

The error code is exactly the same as another issue, which was the one I referenced.

Try running `pip install "spotipy==2.16.1" --force-reinstall`

**Comment by rustjakey** [comment]
Ok, will run that when I get home.

Am i supposed to run that in CMD just normally?

**Comment by rustjakey** [comment]
It worked once, then I tried it again and the same error occured. 

I am strugguling to get that command you send to work though. pip doesnt work on my pc for some reason, so I have to use py but then this happens. 

```C:\WINDOWS\system32>py install "spotipy==2.16.1" --force-reinstall
C:\Users\jakey\AppData\Local\Programs\Python\Python39\python.exe: can't open file 'C:\WINDOWS\system32\install': [Errno 2] No such file or directory```

**Comment by rustjakey** [comment]
I belive I have worked out an issue that may be causing it, although its not the sole cause. 

one of my playlists has non-standard charaters (<->), that seems to break it.

**Comment by MartyMcKnife** [comment]
Is it a playlist name with those characters? If so, the easiest thing to do would be just removing them from the playlist name. I will add a check for invalid characters in the next update
