### ISSUE TITLE
Program will not recognise/work with spotify playlist

### ISSUE THREAD

**Issue by kianslagter** [MartyMcKnife/BeatSaberSpotify#25]
Log is attached. Issue happens every time, any account, any playlist.

Required versions of .NET, Python, and Beat Saber mods are installed.

[beatsaberspotify.log](https://github.com/MartyMcKnife/BeatSaberSpotify/files/6348445/beatsaberspotify.log)

**Comment by MartyMcKnife** [comment]
Looks like spotipy changed its authorization flow, cause this program to break

Can you see if running `pip install "spotipy==2.16.1" --force-reinstall` fixes things?

**Comment by kianslagter** [comment]
Running this works, thanks. Great Program.
