### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ryamonster10** [MartyMcKnife/BeatSaberSpotify#27]
Hi, when I try to download a playlist I get an error and the following is shown in my log file:

https://pastebin.pl/view/d7d2a655

Thanks for any help!
FYI: The app does download about 50% of songs before showing this.

**Comment by MartyMcKnife** [comment]
Looks like you have the same song in the playlist twice, which caused it to break. The program should've automatically caught this error, but obviously it didn't. I'll poke around to see why, but for now, the easiest thing to do would be to remove the duplicate song ("Blister in the Sun"), and run it again
