### ISSUE TITLE
Playlist not finishing

### ISSUE THREAD

**Issue by Surferlul** [MartyMcKnife/BeatSaberSpotify#3]
It gets lots of songs but then it stops...

[beatsaberspotify.log](https://github.com/MartyMcKnife/BeatSaberSpotify/files/4773573/beatsaberspotify.log)

**Comment by MartyMcKnife** [comment]
Looks like the song is not liking a character in one of the songs. Shouldn't be too hard to fix

**Comment by The-Danx** [comment]
I get a similar error
[beatsaverspotify.log](https://github.com/MartyMcKnife/BeatSaberSpotify/files/4775977/beatsaverspotify.log)

**Comment by Surferlul** [comment]
> Looks like the song is not liking a character in one of the songs. Shouldn't be too hard to fix

Can't find anything wrong w/ the songs at the point of the Error...
Here´s the song list:
[Monstercat Radio.txt](https://github.com/MartyMcKnife/BeatSaberSpotify/files/4777013/Monstercat.Radio.txt)
The last song referenced was Fight by Tokyo Machine.
The songs before and after it also don´t look special...

**Comment by Surferlul** [comment]
Nope, I was wrong... I created my own Spotify playlist, pressed "ctrl + a" in the other playlist, and added all the songs to my playlist. Then I just removed the ones that were causing error

**Comment by MartyMcKnife** [comment]
Yeah what I think it is is a special character in the command line. I fixed it for the next update

**Comment by MartyMcKnife** [comment]
Should be fixed now

Download Latest build
