### ISSUE TITLE
I don't even know what to title the issue

### ISSUE THREAD

**Issue by Sutrinu2** [MartyMcKnife/BeatSaberSpotify#4]
[beatsaverspotify.log](https://github.com/MartyMcKnife/BeatSaberSpotify/files/4796746/beatsaverspotify.log)

**Comment by MartyMcKnife** [comment]
Well uh... That's interesting. Looks like the script side of things isn't being run. You did enter the stuff inside the boxes?  Can you send me a photo of what you entered

**Comment by Sutrinu2** [comment]
> Well uh... That's interesting. Looks like the script side of things isn't being run. You did enter the stuff inside the boxes? Can you send me a photo of what you entered

![Screenshot_1](https://user-images.githubusercontent.com/67092524/85086816-56a92c80-b1a1-11ea-986b-88028b2e515b.png)

**Comment by MartyMcKnife** [comment]
Ok this is pretty wacky. I've got no idea how this is happening. Basically, it isn't calling the run.py script as main - something is calling it instead. Assuming the /python folder _only_ contains beatsaver.py, beatsavespotify.py, spotify.py and run.py, can you open up the run.py file in a program like Notepad++, and replace these lines:

`if __name__ == "__main__":`
    `bs.beatsaver_spotify(root_path,uri,username)`
`else:`
    `print("Incorrect Usage. Please enter variables alongside command", flush=True)`

to just 

`bs.beatsaver_spotify(root_path,uri,username)`

**Comment by Sutrinu2** [comment]
I changed the line. After entering the information the app just closes.

**Comment by MartyMcKnife** [comment]
Huh. I've got absolutely no idea what is causing this issue. Can I ask that you double check that have the latest version of python?

Failing that, can you zip the entire folder and send it?

Really curious what the problem is

**Comment by Sutrinu2** [comment]
I downloaded a fresh copy and tried running it again so the results and log are also fresh.

[BeatSaberSpotify.V1.0.1.zip](https://github.com/MartyMcKnife/BeatSaberSpotify/files/4817056/BeatSaberSpotify.V1.0.1.zip)

**Comment by MartyMcKnife** [comment]
If you are still there, try using the latest release. There is a bunch of bug fixes which may fix your problem, or at least generate more informative logs
