### ISSUE TITLE
The app says python is not installed, but it actually is installed

### ISSUE THREAD

**Issue by Vynokris** [MartyMcKnife/BeatSaberSpotify#6]
[beatsaverspotify.log](https://github.com/MartyMcKnife/BeatSaberSpotify/files/5158083/beatsaverspotify.log)
I already have python 3.8 x64 installed on my pc, and it tells me to install python 3.8. How can I resolve this issue?

**Comment by MartyMcKnife** [comment]
Huh. This may be because python hasn't been installed to PATH. Basically, the gui looks for python in your apps registry. If it isn't there, then this will happen

Can I ask that you follow [this guide](https://datatofish.com/add-python-to-windows-path/) - you can follow method 2, as I'm assuming python is already installed

**Comment by Vynokris** [comment]
Well the problem is that I already added python 3.8 to both my system environment variables and user environment variables. I use python a lot to program so it is setup on my pc to be used easily, so I don't see why there would be a problem at this level. For example I can use pip in the command prompt (which would cause an error if the path to python and python/scripts wasn't set). And I can run .py files without any issue...

**Comment by MartyMcKnife** [comment]
Hmmmm. Assuming you are on windows, does it come up if you search for the program in windows home (where it says type here to search)?

**Comment by Vynokris** [comment]
![Annotation 2020-09-02 133233](https://user-images.githubusercontent.com/64845584/91976147-d2d2fb00-ed20-11ea-8397-dbe3cceff5c9.png)
Yup

**Comment by MartyMcKnife** [comment]
Just to clarify - you can run python from the command prompt? 

Seems to be an issue with the latest Windows 10 Update- should the same error come up, this [stackoverflow link](https://stackoverflow.com/a/58773979) should fix it

**Comment by Vynokris** [comment]
It didn't work so I followed the steps in your link, and now I can run python in the command prompt again. So I tried the program again and now it says this:
[beatsaverspotify.log](https://github.com/MartyMcKnife/BeatSaberSpotify/files/5162586/beatsaverspotify.log)
It didn't download anything, it just wrote the songs in the playlist to a txt file.

**Comment by MartyMcKnife** [comment]
Ok. Looks like its timing out when connecting to Spotify. Can you try again? I've just checked, and I'm not experiencing any issues.

**Comment by Vynokris** [comment]
Well I started it again and everything seemed to be going fine until the program froze and this error is now written in the logs:
[beatsaverspotify.log](https://github.com/MartyMcKnife/BeatSaberSpotify/files/5170389/beatsaverspotify.log)
There are a lot of songs in my playlist, I don't know if it could cause a problem. It seems it has an issue with the name of a file or directory. Sorry some parts of the logs are in french.
The program doesn't crash, it just freezes and shows this error in the logs.

**Comment by MartyMcKnife** [comment]
Darn. I thought I fixed that bug. The program calls the path the song title, and if that song title contains bad characters (like < >), then the program errors out. Funnily enough, its the exact same song as the other issue

I'll make a modification so it doesn't stop running if there is an error. At the very least, you should be able to download most of your playlist without it timing out

**Comment by Vynokris** [comment]
Thanks a lot, please notify me when it's done :)

**Comment by MartyMcKnife** [comment]
Should be fixed now with the latest release. I've checked and I'm not getting any errors
